### ISSUE TITLE
[Bug]: The cypress tests in the GitHub deploy action fails after migration

### ISSUE THREAD

**Issue by vedhav** [insightsengineering/teal.gallery#67]
### What happened?

The cypress test works fine in the local after migration. However, it fails in the `Front end test to check if the app works fine` step of the `Deploy Apps 🚀` action.

Note: Please checkout the branch `deploy-apps@main` to have a look at the `deploy.yaml`

### Relevant log output

```
/usr/bin/docker exec  24499702649f2c84a0e77233042211f21cf189e4ce88c3fee9a0faefd9d63197 sh -c "cat /etc/*release | grep ^ID"
Received 0 of 5374796 (0.0%), 0.0 MBs/sec
Received 0 of 179581322 (0.0%), 0.0 MBs/sec
Received 5374796 of 5374796 (100.0%), 4.4 MBs/sec
Cache Size: ~5 MB (5374796 B)
/usr/bin/tar -xf /__w/_temp/0198756b-a49c-4d4d-a76d-4011cb4e789b/cache.tgz -P -C /__w/teal.gallery/teal.gallery -z
Cache restored successfully
Received 46137344 of 179581322 (25.7%), 22.0 MBs/sec
Received 134217728 of 179581322 (74.7%), 42.1 MBs/sec
Received 179581322 of 179581322 (100.0%), 46.0 MBs/sec
Cache Size: ~171 MB (179581322 B)
/usr/bin/tar -xf /__w/_temp/c52[35](https://github.com/insightsengineering/teal.gallery/actions/runs/6049888488/job/16418020314#step:13:36)fd1-2f2c-4[36](https://github.com/insightsengineering/teal.gallery/actions/runs/6049888488/job/16418020314#step:13:37)5-a4b4-1c1ef22c625c/cache.tgz -P -C /__w/teal.gallery/teal.gallery -z
Cache restored successfully
/__t/node/16.20.2/x64/bin/npm ci

added 201 packages, and audited 202 packages in 4s

39 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
/__t/node/16.20.2/x64/bin/npx cypress cache list
┌─────────┬───────────────────┐
│ version │ last used         │
├─────────┼───────────────────┤
│ 12.17.4 │ a few seconds ago │
└─────────┴───────────────────┘
start server command "npm run run-app"
current working directory "/__w/teal.gallery/teal.gallery/RNA-seq/js"
waiting on "http://localhost:3333" with timeout of 500 seconds
/__t/node/16.20.2/x64/bin/npm run run-app

> run-app
> cd .. && Rscript -e "shiny::runApp(port = 3333)"

Loading required package: shiny
Loading required package: ggplot2
Loading required package: teal
Loading required package: teal.data
Loading required package: teal.slice
Loading required package: teal.transform
Loading required package: magrittr

You are using teal version 0.14.0

Attaching package: ‘teal’

The following objects are masked from ‘package:teal.slice’:

    as.teal_slices, teal_slices


Attaching package: ‘teal.modules.hermes’

The following object is masked from ‘package:teal’:

    validate_n_levels

Loading required package: ggmosaic
Loading required package: shinyTree

Attaching package: ‘teal.modules.general’

The following object is masked from ‘package:teal.modules.hermes’:

    tm_g_scatterplot

Warning: replacing previous import ‘S4Arrays::makeNindexFromArrayViewport’ by ‘DelayedArray::makeNindexFromArrayViewport’ when loading ‘SummarizedExperiment’
[INFO] 2023-09-01 13:54:21.1566 pid:20398 token:[] teal.modules.general Initializing tm_front_page
[INFO] 2023-09-01 13:54:21.1675 pid:20398 token:[] teal.modules.hermes Initializing tm_g_pca
[INFO] 2023-09-01 13:54:21.1755 pid:20398 token:[] teal.modules.hermes Initializing tm_g_scatterplot
[INFO] 2023-09-01 13:54:21.1814 pid:20398 token:[] teal.modules.hermes Initializing tm_g_boxplot
[INFO] 2023-09-01 13:54:21.1872 pid:20398 token:[] teal.modules.hermes Initializing tm_g_barplot
[INFO] 2023-09-01 13:54:21.1922 pid:20398 token:[] teal.modules.hermes Initializing tm_g_volcanoplot
[INFO] 2023-09-01 13:54:21.1976 pid:20398 token:[] teal.modules.hermes Initializing tm_g_forest_tte
[INFO] 2023-09-01 13:54:21.2035 pid:20398 token:[] teal.modules.hermes Initializing tm_g_km

Listening on http://127.0.0.1:3333

DevTools listening on ws://127.0.0.1:[38](https://github.com/insightsengineering/teal.gallery/actions/runs/6049888488/job/16418020314#step:13:39)535/devtools/browser/d3dd7f1a-66ca-48ea-aa26-e78beed1bfcf
[20606:0901/135424.579730:ERROR:gpu_memory_buffer_support_x11.cc([44](https://github.com/insightsengineering/teal.gallery/actions/runs/6049888488/job/16418020314#step:13:45))] dri3 extension not supported.
Your configFile is invalid: /__w/teal.gallery/teal.gallery/RNA-seq/tests/cypress.config.js

It threw an error when required, check the stack trace below:

Error: Cannot find module 'cypress'
Require stack:
- /__w/teal.gallery/teal.gallery/RNA-seq/tests/cypress.config.js
- /github/home/.cache/Cypress/12.17.4/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js
- /github/home/.cache/Cypress/12.17.4/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/require_async_child.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:10[48](https://github.com/insightsengineering/teal.gallery/actions/runs/6049888488/job/16418020314#step:13:49):15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at Object.<anonymous> (/__w/teal.gallery/teal.gallery/RNA-seq/tests/cypress.config.js:1:26)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:119:18)
    at loadFile (/github/home/.cache/Cypress/12.17.4/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:89:14)
    at EventEmitter.<anonymous> (/github/home/.cache/Cypress/12.17.4/Cypress/resources/app/node_modules/@packages/server/lib/plugins/child/run_require_async_child.js:116:38)
    at EventEmitter.emit (node:events:[51](https://github.com/insightsengineering/teal.gallery/actions/runs/6049888488/job/16418020314#step:13:52)4:28)
    at process.<anonymous> (/github/home/.cache/Cypress/12.17.4/Cypress/resources/app/node_modules/@packages/server/lib/plugins/util.js:33:22)
    at process.emit (node:events:514:28)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
> Error: Cannot find module 'cypress'

@cicdguy @walkowif
Is this something that you could help out? Is this something to do with cypress installation in the environment/container used to run the pipeline?
